apiVersion: v1
kind: Pod
metadata:
  name: juicer
spec:
  containers:
  - name: juicer
    image: juicer:0.2
    ports:
    - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: juicer
spec:
  selector:
    app: juicer
  ports:
  - port: 9009
    targetPort: 8080
  type: LoadBalancer
